### ISSUE TITLE
Error with image preprocessing

### ISSUE THREAD

**Issue by maoliangjie** [StelaBou/stylegan_directions_face_reenactment#1]
When I use "Face reenactment (self or cross)" with my png and mp4, sometimes it raise "Error with image preprocessing" when "Run reenactment for xxxx images". Is this a problem with my input video

**Comment by StelaBou** [comment]
This means that the preprocessing step is not done properly, there is something wrong with the landmarks detection process. Make sure that your input video is correct (there is a face in each frame) and that the detected landmarks are correct.
Check this [here](https://github.com/StelaBou/stylegan_directions_face_reenactment/blob/33a1f141c41de6fd740d2c313c5ffa476f997d94/libs/utilities/utils_inference.py#L81)
